version: '3.3'
services:
  mysql:
    image: mysql
    container_name: mysql
    # env_file: # using env file instead of env variables
    #     - database.env
    environment:
      MYSQL_DATABASE: 'learndb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'liberi'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'liberi'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'liberi'
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    # Where our data will be persisted
    volumes:
      - my-db-data:/var/lib/mysql
    # restart: always

  postgresql:
    image: postgres # use latest official postgres version
    container_name: postgress
    ports:
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
    # env_file: # using env file instead of env variables
    #     - database.env
    environment:
      - POSTGRES_USER=liberi
      - POSTGRES_PASSWORD=liberi
      - POSTGRES_DB=learndb
    volumes:
      - pg-db-data:/var/lib/postgresql/data/
    # restart: always
  pgadmin:
    image: dpage/pgadmin4 # use latest official postgres version
    container_name: pgadmin_container
    ports:
      - '2345:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    expose:
      # Opens port 3306 on the container
      - '2345'
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - 27017:27017
    expose:
      - '27017'
    volumes:
      - mongodb_data_container:/data/db
    # restart: always
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ch_db
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - '8123:8123' # HTTP interface
      - '9000:9000' # Native client
      - '9005:9005' # PostgresSQL client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    # - ./config.xml:/etc/clickhouse-server/config.xml
    environment:
      CLICKHOUSE_DB: db
      CLICKHOUSE_USER: liberi
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: '1'
      CLICKHOUSE_PASSWORD: liberi
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 5G
        reservations:
          cpus: '3.0'
          memory: 5G
# Names our volume
volumes:
  my-db-data:
  mongodb_data_container:
  pg-db-data: # named volumes can be managed easier using docker-compose
  clickhouse_data:
  clickhouse_logs:
