version: '3.3'
services:
    mysql:
        image: mysql:5.7
        restart: always
        environment:
        MYSQL_DATABASE: 'db'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'liberi'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'liberi'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'PaSw#@92=-3o3i2ioekLKlWdjiac'
        ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
        expose:
        # Opens port 3306 on the container
        - '3306'
        # Where our data will be persisted
        volumes:
        - my-db:/var/lib/mysql

    postgresql:
        image: postgres
        container_name: pg-docker
        ports:
            - "5400:5432"
        environment:
            - POSTGRES_USER=liberi
            - POSTGRES_PASSWORD=liberi
        volumes:
            - ./postgres.conf:/etc/postgresql/postgresql.conf
        command: postgres -c config_file=/etc/postgresql/postgresql.conf
        restart: always
# Names our volume
volumes:
  my-db: